# These are supported funding model platforms

github: [mkehl] # Replace with your GitHub username(s)
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift platform-name/package-name e.g., npm/babel
# custom: ['https://paypal.me/your-link'] # Replace with your custom funding URLs
